import { Cell } from "cell.slint";

export component AppWindow inherits Window {

    in property <int> current-player;

    title: "Tic Tac Toe";
    width: 700px;
    height: 700px;
    background: #313e50;

    GridLayout {
        spacing: 5px;
        padding: 5px;
        Row {
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
        }
        Row {
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
        }
        Row {
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
            Cell {current-player: current-player;}
        }
    }
}