export component Cell inherits Rectangle {
    in property <string> marker: "";
    in property <color> marker-color: black;

    callback clicked;

    Rectangle {
        background: #dcdcdc;
        x: 0px;
        y: 0px;

        Text {
            text: marker;
            font-size: 60px;
            font-weight: 700;
            color: marker-color;
        }

        touch := TouchArea {
            clicked => {
                root.clicked();
            }
            width: 100%;
            height: 100%;
        }
    }
}